export const memeData = [
    {
        characterTag: ["Yoda"],
        isGif: false,
        image: "yoda.jpeg",
        alt: "Old Yoda looking at you.",
    },
    {
        characterTag: ["Obi-Wan Kenobi"],
        isGif: false,
        image: "obione.jpeg",
        alt: "Old Obi-Wan Kenobi looking at you.",
    },
    {
        characterTag: ["Anakin Skywalker"],
        isGif: false,
        image: "anakin.jpeg",
        alt: "Anakin Skywalker looking at you",
    },
    {
        characterTag: ["Emperor Palpatine"],
        isGif: false,
        image: "emperorpalpa.jpeg",
        alt: "Emperor Palpatine saying unlimited power!",
    },
    {
        characterTag: ["Darth Vader"],
        isGif: false,
        image: "darth.jpeg",
        alt: "Darth Vader looking at you with disapproval.",
    },
    {
        characterTag: ["General Grievous"],
        isGif: false,
        image: "general.jpeg",
        alt: "Grievous with his four lightsabers.",
    },
    {
        characterTag: ["Mace Windu"],
        isGif: false,
        image: "windu.jpeg",
        alt: "Mace Windu disapproving of your code.",
    },
    {
        characterTag: ["Jar Jar Binks"],
        isGif: false,
        image: "jar.jpeg",
        alt: "Jar Jar Binks giving a thumbs up.",
    },
    {
        characterTag: ["StormTrooper"],
        isGif: false,
        image: "storm.jpeg",
        alt: "Stormtrooper looking badass",
    },
    {
        characterTag: ["Yoda"],
        isGif: true,
        image: "yoda.gif",
        alt: "Old yoda looking at you.",
    },
    {
        characterTag: ["Obi-Wan Kenobi"],
        isGif: true,
        image: "obi.gif",
        alt: "Obi-Wan Kenobi saying hello.",
    },
    {
        characterTag: ["Anakin Skywalker"],
        isGif: true,
        image: "anak.gif",
        alt: "Anakin Skywalker moving his lightsaber.",
    },
    {
        characterTag: ["Emperor Palpatine"],
        isGif: true,
        image: "palpatine.gif",
        alt: "Palpatine saying unlimited power.",
    },
    {
        characterTag: ["Darth Vader"],
        isGif: true,
        image: "darthva.gif",
        alt: "Darth Vader rising",
    },
    {
        characterTag: ["General Grievous"],
        isGif: true,
        image: "griev.gif",
        alt: "General Grievous with his four lightsabers.",
    },
    {
        characterTag: ["Mace Windu"],
        isGif: true,
        image: "windu.gif",
        alt: "Mace Windu looking at you",
    },
    {
        characterTag: ["Jar Jar Binks"],
        isGif: true,
        image: "jarjar.gif",
        alt: "Jar Jar Binks running for his life",
    },
    {
        characterTag: ["StormTrooper"],
        isGif: true,
        image: "storm.gif",
        alt: "Stormtrooper playing with the sand.",
    },
]